name: "Build artifacts"

on:
  workflow_dispatch:

env:
  TUIFEED_VERSION: "0.4.1"

jobs:
  build-binaries:
    name: Build - ${{ matrix.platform.release_for }}
    strategy:
      matrix:
        platform:
          - release_for: MacOS-x86_64
            os: macos-latest
            target: x86_64-apple-darwin

          - release_for: MacOS-M1
            os: macos-latest
            target: aarch64-apple-darwin

          - release_for: Linux-x86_64
            os: ubuntu-latest
            target: x86_64-unknown-linux-gnu
            deb: amd64

          - release_for: Linux-ARM
            os: ubuntu-latest
            target: aarch64-unknown-linux-gnu
            deb: arm64

    runs-on: ${{ matrix.platform.os }}
    steps:
      - uses: actions/checkout@v2
      - uses: dtolnay/rust-toolchain@stable
        with:
          toolchain: stable
          targets: ${{ matrix.platform.target }}
      - name: install arm toolchain
        if: matrix.platform.os == 'ubuntu-latest' && matrix.platform.target == 'aarch64-unknown-linux-gnu'
        run: |
          sudo apt-get install -y gcc-aarch64-linux-gnu
          echo "CARGO_TARGET_AARCH64_UNKNOWN_LINUX_GNU_LINKER=aarch64-linux-gnu-gcc" >> $GITHUB_ENV
          echo "CC_aarch64_unknown_linux_gnu=aarch64-linux-gnu-gcc" >> $GITHUB_ENV
      - name: Build release
        run: cargo build --release --target ${{ matrix.platform.target }}
      - name: Prepare artifact files
        run: |
          mkdir -p .artifact
          mv target/${{ matrix.platform.target }}/release/tuifeed .artifact/tuifeed
          tar -czf .artifact/tuifeed-v${{ env.TUIFEED_VERSION }}-${{ matrix.platform.target }}.tar.gz -C .artifact tuifeed
          ls -l .artifact/
      - name: build deb
        if: matrix.platform.os == 'ubuntu-latest'
        run: |
          cargo install cargo-deb
          cargo deb --target ${{ matrix.platform.target }}
          cp target/${{ matrix.platform.target }}/debian/*.deb .artifact/tuifeed_${{ env.TUIFEED_VERSION }}_${{ matrix.platform.deb }}.deb
      - name: "Upload artifact"
        uses: actions/upload-artifact@v4
        with:
          if-no-files-found: error
          retention-days: 1
          name: tuifeed-${{ matrix.platform.target }}
          path: .artifact/tuifeed-v${{ env.TUIFEED_VERSION }}-${{ matrix.platform.target }}.tar.gz
      - name: "Upload deb"
        if: matrix.platform.os == 'ubuntu-latest'
        uses: actions/upload-artifact@v4
        with:
          if-no-files-found: error
          retention-days: 1
          name: tuifeed-${{ matrix.platform.target }}-deb
          path: .artifact/tuifeed_${{ env.TUIFEED_VERSION }}_${{ matrix.platform.deb }}.deb
