name: Windows

on: [push, pull_request]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: windows-2019

    steps:
      - uses: actions/checkout@v2
      - uses: dtolnay/rust-toolchain@stable
        with:
          toolchain: stable
          components: rustfmt, clippy
      - name: Build
        run: cargo build
      - name: Run tests
        run: cargo test --no-fail-fast
      - name: Clippy
        run: cargo clippy -- -Dwarnings
